# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='nombre')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='descripci\xf3n')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'attributes',
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
    ]
