# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_model_possible_attribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='nombre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group', verbose_name='parent')),
            ],
            options={
                'db_table': 'groups',
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
