# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_model_group_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='attributes',
            field=models.ManyToManyField(through='app.GroupAttributeValue', to='app.Attribute', verbose_name='attributes'),
        ),
    ]
