# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_create_model_node_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='attributes',
            field=models.ManyToManyField(through='app.NodeAttributeValue', to='app.Attribute', verbose_name='attributes'),
        ),
    ]
