# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_field_attributes_to_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 9, 13, 6, 37, 928330, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 9, 13, 6, 47, 248666, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 9, 13, 6, 50, 216360, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 9, 13, 6, 57, 240639, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
    ]
