# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_field_attributes_to_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 8, 15, 22, 42, 451299, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 8, 15, 22, 50, 123725, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 8, 15, 22, 54, 3605, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupattributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 8, 15, 22, 56, 963167, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 8, 15, 23, 2, 419287, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 8, 15, 23, 6, 259223, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 8, 15, 23, 8, 883200, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeattributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 8, 15, 23, 11, 443078, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possibleattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 8, 15, 23, 14, 91580, tzinfo=utc), verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possibleattributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 8, 15, 23, 16, 371242, tzinfo=utc), verbose_name='updated_at'),
            preserve_default=False,
        ),
    ]
