# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fields_created_at_and_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='default',
            field=models.CharField(max_length=254, null=True, verbose_name='default'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(max_length=254, null=True, verbose_name='type'),
        ),
    ]
