# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_field_default_and_type_to_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='default',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='possibleattributevalue',
            name='value',
            field=models.CharField(max_length=200, verbose_name='value'),
        ),
    ]
