# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_nullable_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='groupattributevalue',
            options={'verbose_name': 'Valor de atributo de grupo', 'verbose_name_plural': 'Valores de atributos de grupo'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Nodo', 'verbose_name_plural': 'Nodos'},
        ),
        migrations.AlterModelOptions(
            name='nodeattributevalue',
            options={'verbose_name': 'Valor de atributo de nodo', 'verbose_name_plural': 'Valores de atributos de nodo'},
        ),
        migrations.AlterModelOptions(
            name='possibleattributevalue',
            options={'verbose_name': 'Posible valor de atributo', 'verbose_name_plural': 'Posibles valores de atributos'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='default',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='valor por defecto'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='attributes',
            field=models.ManyToManyField(through='app.GroupAttributeValue', to='app.Attribute', verbose_name='atributos'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group', verbose_name='padre'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='groupattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Attribute', verbose_name='atributo'),
        ),
        migrations.AlterField(
            model_name='groupattributevalue',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='node',
            name='attributes',
            field=models.ManyToManyField(through='app.NodeAttributeValue', to='app.Attribute', verbose_name='atributos'),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='node',
            name='dns_name',
            field=models.CharField(max_length=200, verbose_name='nombre DNS'),
        ),
        migrations.AlterField(
            model_name='node',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direcci\xf3n MAC'),
        ),
        migrations.AlterField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Attribute', verbose_name='atributo'),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Node', verbose_name='nodo'),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='possibleattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Attribute', verbose_name='atributo'),
        ),
        migrations.AlterField(
            model_name='possibleattributevalue',
            name='value',
            field=models.CharField(max_length=200, verbose_name='valor'),
        ),
    ]
